import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/components/auth/auth-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`bg-[radial-gradient(ellipse_at_bottom_right,_var(--tw-gradient-stops))] from-cerulean-950 via-pink-800 to-cerulean-800 ${inter.className} relative overflow-hidden`}
      >
        <div className="backdrop-blur-3xl">
          <AuthProvider>{children}</AuthProvider>
        </div>
      </body>
    </html>
  );
}
