import { Owner } from "@prisma/client";

export const data: Owner[] = [
  {
    id: 1,
    imageUrl: "https://source.unsplash.com/random/200x200/?man+face+1",
    firstName: "John",
    lastName: "Doe",
    mobileNumber: "555-1234-5678",
    dateOfBirth: new Date(),
    gender: "Prefer not to say",
    email: "JohnDoe@fakemail.com",
    address: "Fake address, 17",
  },
  {
    id: 2,
    imageUrl: "https://source.unsplash.com/random/200x200/?woman+face+2",
    firstName: "Jane",
    lastName: "Smith",
    mobileNumber: "555-9876-5432",
    dateOfBirth: new Date(),
    gender: "Prefer not to say",
    email: "JaneSmith@fakemail.com",
    address: "Fake address, 17",
  },
  {
    id: 3,
    imageUrl: "https://source.unsplash.com/random/200x200/?man+face+3",
    firstName: "Michael",
    lastName: "Johnson",
    mobileNumber: "555-4567-8901",
    dateOfBirth: new Date(),
    gender: "Prefer not to say",
    email: "Michaelnson@fakemail.com",
    address: "Fake address, 17",
  },
  {
    id: 4,
    imageUrl: "https://source.unsplash.com/random/200x200/?woman+face+4",
    firstName: "Emily",
    lastName: "Davis",
    mobileNumber: "555-7890-1234",
    dateOfBirth: new Date(),
    gender: "Prefer not to say",
    email: "Emilyavis@fakemail.com",
    address: "Fake address, 17",
  },
  {
    id: 5,
    imageUrl: "https://source.unsplash.com/random/200x200/?man+face+5",
    firstName: "Daniel",
    lastName: "Brown",
    mobileNumber: "555-2345-6789",
    dateOfBirth: new Date(),
    gender: "Prefer not to say",
    email: "Danielown@fakemail.com",
    address: "Fake address, 17",
  },
  {
    id: 6,
    imageUrl: "https://source.unsplash.com/random/200x200/?woman+face+6",
    firstName: "Olivia",
    lastName: "Miller",
    mobileNumber: "555-8765-4321",
    dateOfBirth: new Date(),
    gender: "Prefer not to say",
    email: "Olivialler@fakemail.com",
    address: "Fake address, 17",
  },
  {
    id: 7,
    imageUrl: "https://source.unsplash.com/random/200x200/?man+face+7",
    firstName: "Christopher",
    lastName: "Wilson",
    mobileNumber: "555-3456-7890",
    dateOfBirth: new Date(),
    gender: "Prefer not to say",
    email: "Christopher@fakemail.com",
    address: "Fake address, 17",
  },
  {
    id: 8,
    imageUrl: "https://source.unsplash.com/random/200x200/?woman+face+8",
    firstName: "Sophia",
    lastName: "Martinez",
    mobileNumber: "555-6789-0123",
    dateOfBirth: new Date(),
    gender: "Prefer not to say",
    email: "Sophiartinez@fakemail.com",
    address: "Fake address, 17",
  },
  {
    id: 9,
    imageUrl: "https://source.unsplash.com/random/200x200/?man+face+9",
    firstName: "Matthew",
    lastName: "Anderson",
    mobileNumber: "555-0123-4567",
    dateOfBirth: new Date(),
    gender: "Prefer not to say",
    email: "Matthewerson@fakemail.com",
    address: "Fake address, 17",
  },
  {
    id: 10,
    imageUrl: "https://source.unsplash.com/random/200x200/?woman+face+10",
    firstName: "Ava",
    lastName: "Taylor",
    mobileNumber: "555-6789-1234",
    dateOfBirth: new Date(),
    gender: "Prefer not to say",
    email: "AvaTaylor@fakemail.com",
    address: "Fake address, 17",
  },
];
